apiVersion: v1
kind: Service
metadata:
  name: {{ include "faster-whisper-server.fullname" . }}
  labels:
    {{- include "faster-whisper-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.fasterWhisper.port }}
      targetPort: whisper-http
      protocol: TCP
      name: whisper-http
  selector:
    {{- include "faster-whisper-server.selectorLabels" . | nindent 4 }}
